# Generated by Django 5.0 on 2023-12-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
