# Generated by Django 5.0 on 2023-12-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedback_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
    ]
