# Generated by Django 5.0 on 2023-12-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_feedback_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='body1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='body2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='body3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='body4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
